version: '3'

services:
  web:
    restart: always
    build: ./backend
    expose:
      - "8181:8181"
    volumes:
      - ./backend:/code
    links:
      - nginx
    command: ["python","app.py"]
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:8081"
    volumes:
      - ./frontend:/usr/share/nginx/html/frontend:ro
    links:
      - web
    depends_on:
      - web